version: "3.7"
services:
  couchbase:
    build:
      context: .
      dockerfile: couchbase.Dockerfile
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET_NAME=ecommerce
      - COUCHBASE_BUCKET_RAM_SIZE=128
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8091"]
      interval: 30s